version: '3.5'

services:
   db:
     build: ./mysql
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
   php:
    build: ./
    ports:
      - '80:80'
    # restart: always
    volumes:
       - ./logs/:/var/log/apache2/
      #  - ./ebt/:/var/www/html/
    depends_on:
      - db
volumes:
    db_data:
